name: Premiere_CI
on:
  pull_request:
jobs:
  deploy:
    Run-on: ubuntu-latest # télécharge depuis github
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - name: Install Dependencies
        run: npm ci
      - name: Execution des tests Unitaires
        run: npm test
      - name: Lint du code
        run: npm run lint
