name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - name: Install deps
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Run unit tests
        run: npm test
      - name: Linter
        run: npm run lint